### ISSUE TITLE
mcp1.open() resets all pins on the device?

### ISSUE THREAD

**Issue by spiral27** [petrockblog/RPi-MCP23S17#6]
Hello and thank you for your library.

I changed your example code in order to set a pin with a single command:

```
from RPiMCP23S17.MCP23S17 import MCP23S17
import time, sys

mcp1 = MCP23S17(bus=0x00, ce=0x00, deviceID=int(sys.argv[1]))
mcp1.open()
mcp1.setDirection(int(sys.argv[2]), mcp1.DIR_OUTPUT)

if sys.argv[3] == "HIGH":
	mcp1.digitalWrite(int(sys.argv[2]), MCP23S17.LEVEL_HIGH)

elif sys.argv[3] == "LOW":
	mcp1.digitalWrite(int(sys.argv[2]), MCP23S17.LEVEL_LOW)
```
so now I can run "python myscript.py 0 0 HIGH", "python myscript.py 0 0 LOW", "python myscript.py 0 1 HIGH", "python myscript.py 0 1 LOW", etc...

But I have a problem because if I run "python myscript.py 0 0 HIGH" and then "python myscript.py 0 1 HIGH", all pins on device 0 (except pin 1 which is my last command) are reseted (not HIGH anymore). 

How can I avoid that?

**Comment by lizzard-winner** [comment]
Can you try my fork? I pulled it from my codebase but I didnt test it seperatly yet. The spi mode is not set correctly in this repo.

**Comment by petrockblog** [comment]
I do not see how I can give support with these information.
