### ISSUE TITLE
GPIO fix for making CE signal work

### ISSUE THREAD

**Issue by jebentancour** [petrockblog/RPi-MCP23S17#7]
Why do you do this?

GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)
GPIO.setup(24, GPIO.OUT)
GPIO.output(24, GPIO.LOW)

If I want to use CE1, do I need to do?:

GPIO.setup(26, GPIO.OUT)
GPIO.output(26, GPIO.LOW)

**Comment by lizzard-winner** [comment]
Yes, see [MCP23S17.py](https://github.com/jonathan-daniel/RPi-MCP23S17/blob/master/MCP23S17.py)
where the pin is a parameter.

**Comment by jebentancour** [comment]
I ended up taking out the GPIOs part.

What made it work was to replace the line:

IOCON_INIT = 0x28 # IOCON_SEQOP and IOCON_HAEN from above

with:

IOCON_INIT = 0x00 # IOCON_BANK_MODE = 0, IOCON_HAEN = 0 address pins disabled

The registers were defined to work with BANK_MODE = 0

**Comment by petrockblog** [comment]
This should be fixed with the recent version.
